rajkamal@debian:~/docker/gitlab-cloudflared$ cat docker-compose.yml 
version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:14.1.3-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.jsrkamal.in'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '2424:22'
    volumes:
      - gitlab_data_cloud:/var/opt/gitlab
      - gitlab_config_cloud:/etc/gitlab
    networks:
      - gitlab_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiYTVhODgxNGU3NGQxODM3M2NiNWI0ZGRhOTEyMmYwMjYiLCJ0IjoiY2Y3NTFkYTctODBhMi00MmZlLWJiMTctZjgyNjU4MDA1MjgyIiwicyI6Ik1UUmpZemRrWTJRdFpqUTNOQzAwWldNNExUazBNV0l0TW1Sa01EQTJOREkwWWpGaCJ9
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: bridge

volumes:
  gitlab_data_cloud:
  gitlab_config_cloud:
