version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:14.1.3-ce.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.62.21.191/'
        gitlab_rails['gitlab_shell_ssh_port'] = 2424
    ports:
      - '80:80'
      - '443:443'
      - '2424:22'
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_config:/etc/gitlab
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: bridge

volumes:
  gitlab_data:
  gitlab_config:
